// SELEÇÃO DE ELEMENTOS DO DOM
export const todoAddTask = document.querySelector("#form-add-task")
export const todoIdTask = document.querySelector("#todo-id-task")
export const todoTitleInputTask = document.querySelector("#todo-title-task")
export const todoDescriptionInputTask = document.querySelector("#todo-description-task")
export const todoEditTask = document.querySelector("#form-edit-task")
export const todoEditIdTask = document.querySelector("#todo-editing-id-task")
export const todoEditTitleTask = document.querySelector('#todo-editing-title-task')
export const todoEditDescriptionTask = document.querySelector('#todo-editing-description-task')
export const todoSearch = document.querySelector("#toolbar")
export const todoListTask = document.querySelector("#todo-task-list")
export const btnCancelEditTask = document.querySelector('#todo-cancel-edit')
export const btnSaveEditTask = document.querySelector('#todo-save-edit')
export const inputSearch = document.querySelector('#input-search')
export const filterSelect = document.querySelector('#filter-select')
export const btnTest =  document.querySelector(".btnTest")
